name: Update LlamaAgent Deployment

on:
  push: 
    branches:
        - main
    paths:
      - "src/bluesky_profile_sentiment_analysis/**"
      - "pyproject.toml"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update deployment
        uses: run-llama/llamactl-deploy@a883f44eb9512d33714db4b0c545a099b93577ec
        with:
          llama-cloud-api-key: ${{ secrets.LLAMA_CLOUD_API_KEY }}
          llama-cloud-project-id: ${{ secrets.LLAMA_CLOUD_PROJECT_ID }}
          deployment-id: "bluesky-profile-sentiment-analysis"
          git-reference: ${{ github.sha }}